version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: Install
          # command: sudo pip3 install kokudo-suuchi-jouhou
          command: sudo pip3 install -i https://test.pypi.org/simple/ kokudo-suuchi-jouhou==0.1.7

      - run:
          name: Test
          command: python3 tests/test.py
