version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: Test
          command: |
            pip3 install -r requirements.txt
            python3 tests/test.py
            python3 -m doctest -v ksj/api.py
            python3 -m doctest -v ksj/shapefile.py
            python3 -m doctest -v ksj/translate.py
