version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: Install
          command: sudo pip3 install ksj
          
      - run:
          name: Test
          command: python3 tests/test.py

